main/urls.py
from django.urls import path
from django.contrib.auth import views
from .views import index, other_page, SPasswordChangeView, LogoutView, SLoginView, RegisterFormView, news_list, news_detail, lessons_shedule, call_shedule, like_news
from django.conf.urls import url
from . import views
app_name = 'main'
urlpatterns =[
    path('news/', news_list, name='news'),
    path('like/', like_news, name='like_news'),
    path('news/<int:pk>/', news_detail, name='news_detail'),
    path('calls/', call_shedule, name='call'),
    path('shedule/', lessons_shedule, name='shedule'),
    path('course/module/order/', views.ModuleOrderView.as_view(),name='module_order'),
    path('course/content/order/', views.ContentOrderView.as_view(), name='content_order'),
    path('courses/', views.CourseListView.as_view(), name='course_list'),
    path('courses/subject/<slug:subject>)/', views.CourseListView.as_view(), name='course_list_subject'),
    path('courses/<slug:slug>/', views.CourseDetailView.as_view(), name='course_detail'),
    path('course/module/<int:module_id>/', views.ModuleContentListView.as_view(), name='module_content_list'),
    path('course/content/<int:id>/delete/', views.ContentDeleteView.as_view(), name='module_content_delete'),
    path('course/module/<int:module_id>/content/<model_name>/create/', views.ContentCreateUpdateView.as_view(), name='module_content_create'),
    path('course/module/<int:module_id>/content/<model_name>/<id>/', views.ContentCreateUpdateView.as_view(), name='module_content_update'),
    path('course/<pk>/module/', views.CourseModuleUpdateView.as_view(), name='course_module_update'),
    path('course/mine/', views.ManageCourseListView.as_view(), name='manage_course_list'),
    path('course/create/', views.CourseCreateView.as_view(), name='course_create'),
    path('course/<pk>/edit/', views.CourseUpdateView.as_view(), name='course_edit'),
    path('course/<pk>/delete/', views.CourseDeleteView.as_view(), name='course_delete'),
    path('accounts/password/change/', SPasswordChangeView.as_view(), name='password_change'),
    path('accounts/logout/', LogoutView.as_view(), name='logout'),
    path('<str:page>/', other_page, name='other'),
    path('accounts/register/', RegisterFormView.as_view(), name='register'),
    path('accounts/login/', SLoginView.as_view(), name='login'),
    path('', index, name='index'),
]

main/models.py
from django.db import models
from django.shortcuts import reverse
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey
from .fields import OrderField
from django.template.loader import render_to_string
from django.utils.safestring import mark_safe

class News(models.Model):
    title = models.CharField(max_length=150, db_index=True, verbose_name='Заголовок новости')
    body = models.TextField(db_index=True, verbose_name='Содержание новости')
    published = models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')
    image = models.ImageField(upload_to='news/%Y/%m/%d', blank=True)
    likes = models.ManyToManyField(User, related_name='likes', blank=True)
    def __str__(self):
        return self.title

    def total_likes(self):
        return self.likes.count()

    class Meta:
        verbose_name_plural = 'Новости'
        verbose_name = 'Новость'
        ordering = ['-published']

class Shedule(models.Model):
    day = models.CharField(max_length=100, db_index=True, verbose_name='День недели')
    lesson1 = models.CharField(max_length=100, db_index=True, verbose_name='Урок 1')
    lesson2 = models.CharField(max_length=100, db_index=True, verbose_name='Урок 2')
    lesson3 = models.CharField(max_length=100, db_index=True, verbose_name='Урок 3')
    lesson4 = models.CharField(max_length=100, db_index=True, verbose_name='Урок 4')
    lesson5 = models.CharField(max_length=100, db_index=True, verbose_name='Урок 5')
    lesson6 = models.CharField(max_length=100, db_index=True, verbose_name='Урок 6')
    lesson7 = models.CharField(max_length=100, db_index=True, verbose_name='Урок 7')

    def __str__(self):
        return self.day

    class Meta:
        verbose_name = 'Расписание'
        verbose_name_plural = 'Расписание'

class Comment(models.Model):
    news = models.ForeignKey(News, related_name='comments', on_delete=models.CASCADE)
    name = models.ForeignKey(User, related_name='name', on_delete=models.PROTECT, verbose_name='Автор')
    body = models.TextField(verbose_name='Текст')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    updated = models.DateTimeField(auto_now=True, verbose_name='Обновлено')
    active = models.BooleanField(default=True, verbose_name='Активный?')

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'
        ordering = ('-created',)

    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.news)

class Call(models.Model):
    lesson = models.IntegerField(verbose_name='Урок', default='1')
    start = models.TimeField(verbose_name='Время начала')
    end = models.TimeField(verbose_name='Время окончания')

    class Meta:
        verbose_name = 'Расписание звонков'
        verbose_name_plural = 'Расписание звонков'

    def __str__(self):
        return 'Call on {} lesson'.format(self.lesson)

class Subject(models.Model):
    title = models.CharField(max_length=200, verbose_name='Название предмета')
    slug = models.SlugField(max_length=200, unique=True, verbose_name='Слаг')
    class Meta:
        ordering = ['title']
        verbose_name='Предмет'
        verbose_name_plural='Предметы'

    def __str__(self):
        return self.title

class Course(models.Model):
    owner = models.ForeignKey(User, related_name='courses_created', on_delete=models.CASCADE, verbose_name='Автор')
    subject = models.ForeignKey(Subject, related_name='courses', on_delete=models.CASCADE, verbose_name='Предмет')
    title = models.CharField(max_length=200, verbose_name='Название')
    slug = models.SlugField(max_length=200, unique=True, verbose_name='Слаг')
    overview = models.TextField(verbose_name='Описание')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    students = models.ManyToManyField(User, related_name='courses_joined', blank=True)
    class Meta:
        ordering = ['-created']
        verbose_name='Курс'
        verbose_name_plural='Курсы'

    def __str__(self):
        return self.title

class Module(models.Model):
    course = models.ForeignKey(Course, related_name='modules', on_delete=models.CASCADE, verbose_name='Курс')
    title = models.CharField(max_length=200, verbose_name='Название')
    description = models.TextField(blank=True, verbose_name='Описание')
    order = OrderField(blank=True, for_fields=['course'])
    def __str__(self):
        return '{}. {}'.format(self.order, self.title)
    class Meta:
        verbose_name='Модуль'
        verbose_name_plural='Модули'
        ordering = ['order']


class Content(models.Model):
    module = models.ForeignKey(Module, related_name='contents', on_delete=models.CASCADE, verbose_name='Модуль')
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE, limit_choices_to={'model__in':('text', 'video', 'image', 'file')})
    object_id = models.PositiveIntegerField()
    item = GenericForeignKey('content_type', 'object_id')
    order = OrderField(blank=True, for_fields=['module'])
    class Meta:
        verbose_name='Контент'
        verbose_name_plural='Контент'
        ordering = ['order']


class ItemBase(models.Model):
    owner = models.ForeignKey(User, related_name='%(class)s_related', on_delete=models.CASCADE, verbose_name='Автор')
    title = models.CharField(max_length=250, verbose_name='Название')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Создано')
    updated = models.DateTimeField(auto_now=True, verbose_name='Обновлено')
    class Meta:
        abstract = True

    def __str__(self):
        return self.title

    def render(self):
        return render_to_string('courses/content/{}.html'.format(self._meta.model_name), {'item': self}) 

class Text(ItemBase):
    content = models.TextField(verbose_name='Содержание')

class File(ItemBase):
    file = models.FileField(upload_to='files', verbose_name='Файл')
class Image(ItemBase):
    file = models.FileField(upload_to='images', verbose_name='Изображение')

class Video(ItemBase):
    url = models.URLField(verbose_name='URL Видео')

main/forms.py
from .models import Comment, Course, Module
from django import forms
from django.forms.models import inlineformset_factory

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)

ModuleFormSet = inlineformset_factory(Course, Module, fields=['title', 'description'],  extra=2, can_delete=True) 

main/templates/layout/base.html
{% load static %}
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" type="text/css" href="{% static 'main/style.css '%}">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <link href="https://fonts.googleapis.com/css?family=Comfortaa:500,700&display=swap&subset=cyrillic" rel="stylesheet">
  <title>{% block title %}{% endblock %}</title>
</head>
<body>
  {% if user.is_authenticated %}
  <!-- Sidebar  -->
    <nav id="sidebar">
      <div id="dismiss">
        <i class="fa fa-arrow-left"></i>
      </div>

      <div class="sidebar-header">
        <a href="{% url 'main:index' %}"><h3 class="font-weight-light">Мой класс</h3></a>
      </div>

      <ul class="list-unstyled components">
        <li class="active">
          <a href="{% url 'main:index' %}">Главная</a>
        </li>
        <li>
          <a href="{% url 'main:news' %}">Новости</a>
        </li>
        <li>
          <a href="{% url 'main:other' page='about' %}">О сайте</a>
        </li>
        <li>
          <a href="#pageSubmenu1" data-toggle="collapse" aria-expanded="false">Расписание <i class="fa fa-caret-down"></i></a>
          <ul class="collapse list-unstyled" id="pageSubmenu1">
            <li>
              <a href="{% url 'main:shedule' %}">Расписание уроков</a>
            </li>
            <li>
              <a href="{% url 'main:call' %}">Расписание звонков</a>
            </li>
          </ul>
        </li>
        <li>
          <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false">Профиль <i class="fa fa-caret-down"></i></a>
          <ul class="collapse list-unstyled" id="pageSubmenu">
            <li>
              <a href="{% url 'main:password_change' %}">Изменить пароль</a>
            </li>
            <li>
              <a href="{% url 'main:logout' %}">Выйти</a>
            </li>
          </ul>
        </li>
        {% if perms.main.add_course %}
          <li>
            <a href="#course" data-toggle="collapse" aria-expanded="false">Курсы <i class="fa fa-caret-down"></i></a>
            <ul class="collapse list-unstyled" id="course">
              <li>
                <a href="{% url 'main:manage_course_list' %}">Управление курсами</a>
              </li>
              <li>
                <a href="{% url 'main:course_list' %}">Просмотр курсов</a>
              </li>
            </ul>
          </li>
        {% else %}
          <li>
            <a href="#course-student" data-toggle="collapse" aria-expanded="false">Курсы <i class="fa fa-caret-down"></i></a>
            <ul class="collapse list-unstyled" id="course-student">
              <li>
                <a href="{% url 'main:course_list' %}">Курсы</a>
              </li>
              <li>
                <a href="{% url 'student_course_list' %}">Просмотренные курсы</a>
              </li>
            </ul>
          </li>
        {% endif %}
        {% if user.is_staff %}
        <li>
          <a href="#pageSub" data-toggle="collapse" aria-expanded="false">Администрирование <i class="fa fa-caret-down"></i></a>
          <ul class="collapse list-unstyled" id="pageSub">
            <li>
              <a href="{% url 'main:register' %}">Регистрация учеников</a>
            </li>
            <li>
              <a href="admin/">Административная страница</a>
            </li>
          </ul>
        </li>
        {% endif %}
        <li>
          <div class="switch ml-2 mt-2 mb-1">
            <input type="checkbox" id="switch-1" class="switch-check">
          </div>
        </li>
      </ul>
    </nav>
    <nav class="navbar navbar-expand-lg cont dark">
      <div class="container-fluid">
        <button type="button" id="sidebarCollapse" class="btn btn-light">
          <i class="fa fa-align-left"></i>
        </button>
        <a href="{% url 'main:index' %}" class="navbar-brand">Мой класс</a>
      </div>
    </nav>
    <div class="container-fluid p-0 cont">
      {% bootstrap_messages %}
      {% block content %}
      {% endblock %}
    </div>
    <footer class="pr-3">
      <p class="text-right font-italic pt-1 text-white h-100 p-0">&copy; Азат Юлдашев, 2019 г.</p>
    </footer>
  {% else %}
    <nav class="navbar navbar-expand-lg navb">
      <div class="container-fluid">
        <h1 class="navbar-brand m-0">Мой класс</h1>
      </div>
    </nav>
    <div  class="container">
      <div  class="row justify-content-center">
        <div class="col-xs-10 col-sm-10 col-md-7 col-lg-5 col-xs-5">
          {% block main %}
          {% endblock %}
        </div>
      </div>
    </div>
  {% endif %}
  <div class="overlay"></div>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.concat.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.min.css">
  <script type="text/javascript">
    $(document).ready(function(event){
      $(document).on('click', '#like', function(event){
        event.preventDefault();
        var pk = $(this).attr('value');
        $.ajax({
          type: 'POST',
          url: '{% url "main:like_news" %}',
          data: {'id': pk, 'csrfmiddlewaretoken': '{{ csrf_token }}'},
          dataType: 'json',
          success: function(response){
            $('#like-section').html(response['form']);
            console.log($('#like-section').html(response['form']));
          },
          error: function(rs, e){
            console.log(rs, responseText);
          },
        });
      });
    });
  </script>
  <script>
    $(document).ready(function() {
      {% block domready %}
      {% endblock %}
    });
  </script>
  <script type="text/javascript">
    $(document).ready(function () {

      $('#dismiss, .overlay').on('click', function () {
        $('#sidebar').removeClass('active');
        $('.overlay').removeClass('active');
      });

      $('#sidebarCollapse').on('click', function () {
        $('#sidebar').addClass('active');
        $('.overlay').addClass('active');
        $('.collapse.in').toggleClass('in');
        $('a[aria-expanded=true]').attr('aria-expanded', 'false');
      });
    });
  </script>
  <script type="text/javascript">
    $("#sidebar").mCustomScrollbar({
      theme: "minimal"
    });
  </script>
  <script src="{% static 'js/script.js '%}"></script>
</body>

</html>