main/urls.py
from django.urls import path
from django.contrib.auth import views
from .views import index, other_page, SPasswordChangeView, LogoutView, SLoginView, RegisterFormView, news_list, news_detail, lessons_shedule, call_shedule, like_news
from django.conf.urls import url
from . import views
app_name = 'main'
urlpatterns =[
    path('news/', news_list, name='news'),
    path('like/', like_news, name='like_news'),
    path('news/<int:pk>/', news_detail, name='news_detail'),
    path('calls/', call_shedule, name='call'),
    path('shedule/', lessons_shedule, name='shedule'),
    path('course/module/order/', views.ModuleOrderView.as_view(),name='module_order'),
    path('course/content/order/', views.ContentOrderView.as_view(), name='content_order'),
    path('courses/', views.CourseListView.as_view(), name='course_list'),
    path('courses/subject/<slug:subject>)/', views.CourseListView.as_view(), name='course_list_subject'),
    path('courses/<slug:slug>/', views.CourseDetailView.as_view(), name='course_detail'),
    path('course/module/<int:module_id>/', views.ModuleContentListView.as_view(), name='module_content_list'),
    path('course/content/<int:id>/delete/', views.ContentDeleteView.as_view(), name='module_content_delete'),
    path('course/module/<int:module_id>/content/<model_name>/create/', views.ContentCreateUpdateView.as_view(), name='module_content_create'),
    path('course/module/<int:module_id>/content/<model_name>/<id>/', views.ContentCreateUpdateView.as_view(), name='module_content_update'),
    path('course/<pk>/module/', views.CourseModuleUpdateView.as_view(), name='course_module_update'),
    path('course/mine/', views.ManageCourseListView.as_view(), name='manage_course_list'),
    path('course/create/', views.CourseCreateView.as_view(), name='course_create'),
    path('course/<pk>/edit/', views.CourseUpdateView.as_view(), name='course_edit'),
    path('course/<pk>/delete/', views.CourseDeleteView.as_view(), name='course_delete'),
    path('accounts/password/change/', SPasswordChangeView.as_view(), name='password_change'),
    path('accounts/logout/', LogoutView.as_view(), name='logout'),
    path('<str:page>/', other_page, name='other'),
    path('accounts/register/', RegisterFormView.as_view(), name='register'),
    path('accounts/login/', SLoginView.as_view(), name='login'),
    path('', index, name='index'),
]

main/models.py
from django.db import models
from django.shortcuts import reverse
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey
from .fields import OrderField
from django.template.loader import render_to_string
from django.utils.safestring import mark_safe

class News(models.Model):
    title = models.CharField(max_length=150, db_index=True, verbose_name='Заголовок новости')
    body = models.TextField(db_index=True, verbose_name='Содержание новости')
    published = models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')
    image = models.ImageField(upload_to='news/%Y/%m/%d', blank=True)
    likes = models.ManyToManyField(User, related_name='likes', blank=True)
    def __str__(self):
        return self.title

    def total_likes(self):
        return self.likes.count()

    class Meta:
        verbose_name_plural = 'Новости'
        verbose_name = 'Новость'
        ordering = ['-published']

class Shedule(models.Model):
    day = models.CharField(max_length=100, db_index=True, verbose_name='День недели')
    lesson1 = models.CharField(max_length=100, db_index=True, verbose_name='Урок 1')
    lesson2 = models.CharField(max_length=100, db_index=True, verbose_name='Урок 2')
    lesson3 = models.CharField(max_length=100, db_index=True, verbose_name='Урок 3')
    lesson4 = models.CharField(max_length=100, db_index=True, verbose_name='Урок 4')
    lesson5 = models.CharField(max_length=100, db_index=True, verbose_name='Урок 5')
    lesson6 = models.CharField(max_length=100, db_index=True, verbose_name='Урок 6')
    lesson7 = models.CharField(max_length=100, db_index=True, verbose_name='Урок 7')

    def __str__(self):
        return self.day

    class Meta:
        verbose_name = 'Расписание'
        verbose_name_plural = 'Расписание'

class Comment(models.Model):
    news = models.ForeignKey(News, related_name='comments', on_delete=models.CASCADE)
    name = models.ForeignKey(User, related_name='name', on_delete=models.PROTECT, verbose_name='Автор')
    body = models.TextField(verbose_name='Текст')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    updated = models.DateTimeField(auto_now=True, verbose_name='Обновлено')
    active = models.BooleanField(default=True, verbose_name='Активный?')

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'
        ordering = ('-created',)

    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.news)

class Call(models.Model):
    lesson = models.IntegerField(verbose_name='Урок', default='1')
    start = models.TimeField(verbose_name='Время начала')
    end = models.TimeField(verbose_name='Время окончания')

    class Meta:
        verbose_name = 'Расписание звонков'
        verbose_name_plural = 'Расписание звонков'

    def __str__(self):
        return 'Call on {} lesson'.format(self.lesson)

class Subject(models.Model):
    title = models.CharField(max_length=200, verbose_name='Название предмета')
    slug = models.SlugField(max_length=200, unique=True, verbose_name='Слаг')
    class Meta:
        ordering = ['title']
        verbose_name='Предмет'
        verbose_name_plural='Предметы'

    def __str__(self):
        return self.title

class Course(models.Model):
    owner = models.ForeignKey(User, related_name='courses_created', on_delete=models.CASCADE, verbose_name='Автор')
    subject = models.ForeignKey(Subject, related_name='courses', on_delete=models.CASCADE, verbose_name='Предмет')
    title = models.CharField(max_length=200, verbose_name='Название')
    slug = models.SlugField(max_length=200, unique=True, verbose_name='Слаг')
    overview = models.TextField(verbose_name='Описание')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    students = models.ManyToManyField(User, related_name='courses_joined', blank=True)
    class Meta:
        ordering = ['-created']
        verbose_name='Курс'
        verbose_name_plural='Курсы'

    def __str__(self):
        return self.title

class Module(models.Model):
    course = models.ForeignKey(Course, related_name='modules', on_delete=models.CASCADE, verbose_name='Курс')
    title = models.CharField(max_length=200, verbose_name='Название')
    description = models.TextField(blank=True, verbose_name='Описание')
    order = OrderField(blank=True, for_fields=['course'])
    def __str__(self):
        return '{}. {}'.format(self.order, self.title)
    class Meta:
        verbose_name='Модуль'
        verbose_name_plural='Модули'
        ordering = ['order']


class Content(models.Model):
    module = models.ForeignKey(Module, related_name='contents', on_delete=models.CASCADE, verbose_name='Модуль')
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE, limit_choices_to={'model__in':('text', 'video', 'image', 'file')})
    object_id = models.PositiveIntegerField()
    item = GenericForeignKey('content_type', 'object_id')
    order = OrderField(blank=True, for_fields=['module'])
    class Meta:
        verbose_name='Контент'
        verbose_name_plural='Контент'
        ordering = ['order']


class ItemBase(models.Model):
    owner = models.ForeignKey(User, related_name='%(class)s_related', on_delete=models.CASCADE, verbose_name='Автор')
    title = models.CharField(max_length=250, verbose_name='Название')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Создано')
    updated = models.DateTimeField(auto_now=True, verbose_name='Обновлено')
    class Meta:
        abstract = True

    def __str__(self):
        return self.title

    def render(self):
        return render_to_string('courses/content/{}.html'.format(self._meta.model_name), {'item': self}) 

class Text(ItemBase):
    content = models.TextField(verbose_name='Содержание')

class File(ItemBase):
    file = models.FileField(upload_to='files', verbose_name='Файл')
class Image(ItemBase):
    file = models.FileField(upload_to='images', verbose_name='Изображение')

class Video(ItemBase):
    url = models.URLField(verbose_name='URL Видео')

main/forms.py
from .models import Comment, Course, Module
from django import forms
from django.forms.models import inlineformset_factory

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)

ModuleFormSet = inlineformset_factory(Course, Module, fields=['title', 'description'],  extra=2, can_delete=True) 

main/templates/main/about.html
{% extends 'layout/base.html' %}
{% block title %}О сайте{% endblock %}
{% block content %}
<div class="text-center about">
  <div class="mt-2">
    <h3>О сайте</h3>
  </div>
  <div class="mt-2">
    <p>Сайт создал ученик 7В класса Юлдашев Азат.</p>
    <p>При возникновении ошибок на сайте сообщите мне: <a href="mailto:moyklass147@gmail.com">moyklass147@gmail.com</a></p>
  </div>
</div>
{% endblock %}

main/templates/main/call.html
{% extends 'layout/base.html' %}
{% block title %}Расписание звонков{% endblock %}
{% block content %}
<div class="text-center shedule-text mt-1">
  <h1>Расписание звонков</h1>
</div>
<div class="row justify-content-center mx-auto">
  <div class="col-xs-10 col-sm-10 col-md-4 col-lg-3 col-xl-2 my-3">
    <div class="card cards" style="width: 18rem;">
      <div class="card-header cards-header">
        Расписание звонков
      </div>
      <ul class="list-group list-group-flush">
        {% for i in call %}
          <li class="list-group-item cards">{{ i.lesson }}) Начало {{ i.start }} Конец {{ i.end }}</li>
        {% endfor %}
      </ul>
    </div>
  </div>
</div>
{% endblock %}

main/templates/main/index.html
{% extends 'layout/base.html' %}
{% block title %}Главная{% endblock %}
{% block content %}
<div class="index">
  <div class="jumbotron mb-3">
    <h1 class="display-4 text-center info-text">Добро пожаловать!</h1>
    <hr style="background-color: #b9b9b9;">
    <p class="lead text-center">Добро пожаловать на сайт 7В класса. Мы рады приветствовать тебя здесь. На этом сайте ты можешь узнать последние новости класса, раписание звонков и уроков, а также подучить предметы или расширить свои знания.</p>
  </div>
  <div class="container-fluid">
    <div class="row justify-content-center mx-auto">
      <div class="col-xs-10 col-sm-10 col-md-4 col-lg-3 col-xl-2">
        <div class="card text-center mt-3 mb-3 cards">
          <div class="card-body">
            <h5 class="card-title">Расписание</h5>
            <hr width='100%'>
            <p class="card-text">Узнайте расписание уроков на сегодня.</p>
            <a href="{% url 'main:shedule' %}"><button class="btn-hover color-8 m-0">Перейти</button></a>
          </div>
        </div>
      </div>
      <div class="col-xs-10 col-sm-10 col-md-4 col-lg-3 col-xl-2">
        <div class="card text-center mt-3 mb-3 cards">
          <div class="card-body">
            <h5 class="card-title">Новости</h5>
            <hr width='100%'>
            <p class="card-text">Узнайте последние новости класса.</p>
            <a href="{% url 'main:news' %}"><button class="btn-hover color-8 m-0">Перейти</button></a>
          </div>
        </div>
      </div>
      <div class="col-xs-10 col-sm-10 col-md-4 col-lg-3 col-xl-2">
        <div class="card text-center mt-3 mb-3 cards">
          <div class="card-body">
            <h5 class="card-title">О сайте</h5>
            <hr width='100%'>
            <p class="card-text">Узнайте информацию о нашем сайте.</p>
            <a href="{% url 'main:other' page='about' %}"><button class="btn-hover color-8 m-0">Перейти</button></a>

          </div>
        </div>
      </div>
      <div class="col-xs-10 col-sm-10 col-md-4 col-lg-3 col-xl-2">
        <div class="card text-center mt-3 mb-3 cards">
          <div class="card-body">
            <h5 class="card-title">Курсы</h5>
            <hr width='100%'>
            <p class="card-text">Пройдите курсы и расширьте свои знания.</p>
            <a href="{% url 'main:course_list' %}"><button class="btn-hover color-8 m-0">Перейти</button></a>

          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="container-fluid text-center newss">
    <h3 class="py-2 text-white">Последние новости:</h3>
  </div>
  <div class="row justify-content-center mx-auto">
    {% for i in last %}
      <div class="col-xs-10 col-sm-10 col-md-4 col-lg-3 col-xl-2 my-3">
        <div class="card cards">
          <div class="card-header cards-header">
            {{ i.title }}
          </div>
          <div class="card-body">
            <p class="mb-2">{{ i.body }}</p>
          </div>
          <div class="card-footer cards-footer">
            <p class="text-muted mb-1">{{ i.published }}</p>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

main/templates/main/like_section.html
<form action="{% url 'main:like_news'%}" method="post">
  {% csrf_token %}
  {% if is_liked %}
    Нравиться<button type="submit" id="like" name="news_id" value="{{ news.id }}" class="fa fa-thumbs-up btn dislike"></button>{{ total_likes }}
  {% else %}
    Нравиться<button type="submit" id="like" name="news_id" value="{{ news.id }}" class="fa fa-thumbs-up like btn"></button>{{ total_likes }}
  {% endif %}
</form>

main/templates/main/logout.html
{% extends 'layout/base.html' %}
{% block title %}Выход{% endblock %}

{% block content %}
<h2>Выход</h2>
<p>Вы успешно вышли из аккаунта.</p>
<a href="{% url 'main:login' %}">Войти снова</a>
{% endblock %}

main/templates/main/news.html
{% extends 'layout/base.html' %}

{% block title %}Новости{% endblock %}

{% block content %}
<div class="text-center news-text mt-1">
  <h1>Новости класса</h1>
</div>
<div class="row justify-content-center mx-auto">
  <div class="col-xs-10 col-sm-10 col-md-6 col-lg-4 col-xl-4">
    {% for new in news.object_list %}
      <div class="card mt-3 news-body cards">
        <h4 class="card-header cards-header">
          {{ new.title }}
        </h4>
        {% if new.image %}<img class="card-img-top" src="{{ new.image.url }}" alt="Card image cap">{% endif %}
        <div class="card-body">
          <p class="card-text">{{ new.body|truncatewords:5 }}</p>
          <a href="{% url 'main:news_detail' pk=new.pk %}"><button class="btn-hover color-8 m-0">Подробнее</button></a>
        </div>
        <div class="card-footer text-muted news-footer">
          {{ new.published }}
        </div>
      </div>
    {% endfor %}
    {% if is_paginated %}
      <nav class="mt-3">
        <ul class="pagination">
          <li class="page-item {% if not prev_url %}disabled{% endif %}">
            <a class="page-link paginator {% if prev_url %}text-white{% endif %}" href="{{ prev_url }}" tabindex="-1" aria-disabled="true">
              <span aria-hidden="true">&laquo;</span>
            </a>
          </li>

          {% for n in news.paginator.page_range %}
            {% if news.number == n %}
              <li class="page-item active" aria-current="page">
                <a class="page-link paginator-active" href="?page={{ n }}">{{ n }}<span class="sr-only">(current)</span></a>
              </li>
            {% elif n > news.number|add:-3 and n < news.number|add:3 %}
              <li class="page-item">
                <a class="page-link paginator text-white" href="?page={{ n }}">{{ n }}</a>
              </li>
            {% endif %}
          {% endfor %}

          <li class="page-item {% if not next_url %}disabled{% endif %}">
            <a class="page-link paginator {% if next_url %}text-white{% endif %}" href="{{ next_url }}" href="{{ next_url }}">
              <span aria-hidden="true">&raquo;</span>
            </a>
          </li>
        </ul>
      </nav>
    {% endif %}
  </div>
</div>
{% endblock %}

main/templates/main/news_detail.html
{% extends 'layout/base.html' %}
{% load bootstrap4 %}
{% block title %}{{ news.title }}{% endblock %}
{% block content %}
<div class="text-center detail">
  <div class="mt-2">
    <h1>{{ news.title }}</h1>
  </div>
  <div class='row justify-content-center mx-auto'>
    <div class="col-xs-10 col-sm-10 col-md-6 col-lg-4 col-xl-4 mt-1">
        {% if news.image %}<img src="{{news.image.url}}" class='w-100 rounded'>{% endif %}
    </div>
  </div>
  <p class='mt-1'>{{ news.body }}</p>
  <p class='text-muted'>{{ news.published }}</p>
  <div id="like-section" class="">
    {% include 'main/like_section.html' %}
  </div>
</div>
<hr style='background-color: #777' class="mb-1">
<div class="commentaries text-white">
  {% with comments.count as total_comments %}
    <h2 class='text-center'>Комментарии: {{ total_comments }}</h2>
  {% endwith %}
  {% for comment in comments %}
    <div class="comment">
      <p class="info">
        {{ comment.name }}
        {{ comment.created }}
      </p>
      {{ comment.body|linebreaks }}
    </div>
  {% empty %}
    <p class='text-center'>Нет комментариев.</p>
  {% endfor %}

  {% if new_comment %}
    <h2 class="text-center mt-2">Комментарий добавлен.</h2>
  {% else %}
    <h2 class='text-center mt-2'>Добавить новый комментарий</h2>
    <h5 class='text-center'>Введите текст комментария</h5>
    <form action="." method="post" class='container-fluid text-center'>
      <div class="form-group">
        <label class="sr-only" for="id_body">Текст</label>
        <textarea name="body" cols="40" rows="10" class="form-control textar" placeholder="Текст" title="" required="" id="id_body"></textarea>
      </div>
      {% csrf_token %}
      <button class="btn-hover color-8 m-0" type="
      ">Отправить</button>
    </form>
  {% endif %}
</div>
{% endblock %}

main/templates/main/password_change.html
{% extends 'layout/base.html' %}
{% load bootstrap4 %}
{% block title %}Смена пароля{% endblock %}
{% block content %}
<div class="text-center password mt-2">
    <h2>Смена пароля пользователя {{ user.username }}</h2>
</div>
<div class="container-fluid mx-auto mb-3 mt-2 password-change">

  <form method="post">
    {% csrf_token %}
    <div class="password-form">
      {% bootstrap_form form layout='horizontal' %}
    </div>
    <button type="submit" class="btn-hover btn-block color-8 mx-auto shrift">Сменить пароль</button>
  </form>
</div>
{% endblock %}

main/templates/main/shedule.html
{% extends 'layout/base.html' %}
{% block title %}Расписание{% endblock %}
{% block content %}
<div class="text-center shedule-text mt-1">
  <h1>Расписание уроков</h1>
</div>
<div class="row justify-content-center mx-auto">
    {% for s in shedule %}
      <div class="col-xs-10 col-sm-10 col-md-4 col-lg-3 col-xl-2 my-3">
        <div class="card cards">
          <div class="card-header cards-header">
            {{ s.day }}
          </div>
          <ul class="list-group list-group-flush">
            <li class="list-group-item cards">1) {{ s.lesson1 }}</li>
            <li class="list-group-item cards">2) {{ s.lesson2 }}</li>
            <li class="list-group-item cards">3) {{ s.lesson3 }}</li>
            <li class="list-group-item cards">4) {{ s.lesson4 }}</li>
            <li class="list-group-item cards">5) {{ s.lesson5 }}</li>
            <li class="list-group-item cards">6) {{ s.lesson6 }}</li>
            <li class="list-group-item cards">7) {{ s.lesson7 }}</li>
          </ul>
        </div>
      </div>
    {% endfor %}
</div>
{% endblock %}